# Generated by Django 6.0.3 on 2026-03-26 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cita_carga', models.CharField(max_length=100)),
                ('dni_chofer', models.CharField(max_length=20)),
                ('nombre_chofer', models.CharField(max_length=150)),
                ('matricula_tractora', models.CharField(max_length=20)),
                ('matricula_remolque', models.CharField(blank=True, max_length=20)),
                ('agencia', models.CharField(max_length=150)),
                ('muelle', models.CharField(max_length=20)),
                ('entrada', models.DateTimeField(auto_now_add=True)),
                ('documentacion_ok', models.BooleanField(blank=True, null=True)),
                ('precinto', models.CharField(blank=True, max_length=100)),
                ('salida', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
