# Generated by Django 6.0.3 on 2026-06-11 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accesos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Muelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10, unique=True)),
                ('tipo', models.CharField(choices=[('RECEPCION', 'Recepción'), ('EXPEDICION', 'Expedición'), ('MIXTO', 'Mixto')], default='MIXTO', max_length=10)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['numero'],
            },
        ),
        migrations.AlterModelOptions(
            name='visit',
            options={'ordering': ['-entrada']},
        ),
        migrations.RemoveField(
            model_name='visit',
            name='cita_carga',
        ),
        migrations.AddField(
            model_name='visit',
            name='agencia_mensajeria',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='visit',
            name='bultos_declarados',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='bultos_reales',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='cliente',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='visit',
            name='estado',
            field=models.CharField(choices=[('ESPERANDO', 'Esperando'), ('OPERANDO', 'Operando'), ('LISTO', 'Listo para salir'), ('SALIDO', 'Salido')], default='ESPERANDO', max_length=10),
        ),
        migrations.AddField(
            model_name='visit',
            name='num_pedidos',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='numero_contenedor',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='visit',
            name='orden_compra',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='visit',
            name='puerto_origen',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='visit',
            name='tipo',
            field=models.CharField(choices=[('ENTRADA', 'Entrada — Recepción'), ('SALIDA', 'Salida — Expedición')], default='ENTRADA', max_length=10),
        ),
        migrations.AddField(
            model_name='visit',
            name='tipo_salida',
            field=models.CharField(blank=True, choices=[('GRAN_CUENTA', 'Gran cuenta'), ('PAQUETERIA', 'Paquetería')], max_length=15),
        ),
        migrations.CreateModel(
            name='Incidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('DOCUMENTACION', 'Documentación incorrecta'), ('BULTOS', 'Diferencia de bultos'), ('AVERIA', 'Avería del vehículo'), ('CARGA', 'Problema con la carga'), ('ESPERA', 'Espera excesiva'), ('OTRO', 'Otro')], max_length=15)),
                ('descripcion', models.TextField()),
                ('urgente', models.BooleanField(default=False)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('resuelta', models.BooleanField(default=False)),
                ('visita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidencias', to='accesos.visit')),
            ],
            options={
                'ordering': ['-urgente', '-creada_en'],
            },
        ),
        migrations.AlterField(
            model_name='visit',
            name='muelle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='visitas', to='accesos.muelle'),
        ),
    ]
