# Generated by Django 6.0.3 on 2026-06-12 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accesos', '0002_muelle_alter_visit_options_remove_visit_cita_carga_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick', models.CharField(max_length=30, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('cif', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('contacto', models.CharField(blank=True, max_length=100)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Agencia',
                'ordering': ['nick'],
            },
        ),
        migrations.CreateModel(
            name='Chofer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('matricula_habitual', models.CharField(blank=True, max_length=20)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Chofer',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('sucursal', models.CharField(blank=True, max_length=100)),
                ('tipo', models.CharField(choices=[('TRD', 'Gran cuenta (TRD)'), ('BLK', 'Distribuidores (BLK)'), ('BDP', 'Paquetería (BDP)'), ('EXW', 'Exportación (EXW)')], default='BLK', max_length=5)),
                ('direccion', models.CharField(blank=True, max_length=200)),
                ('cp', models.CharField(blank=True, max_length=10)),
                ('poblacion', models.CharField(blank=True, max_length=100)),
                ('provincia', models.CharField(blank=True, max_length=100)),
                ('pais', models.CharField(default='ESPAÑA', max_length=50)),
                ('necesita_plataforma', models.BooleanField(default=False)),
                ('accede_trailer', models.BooleanField(default=True)),
                ('observaciones', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Hub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('entidad', models.CharField(blank=True, max_length=150)),
                ('direccion', models.CharField(blank=True, max_length=200)),
                ('poblacion', models.CharField(blank=True, max_length=100)),
                ('pais', models.CharField(default='ESPAÑA', max_length=50)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Hub',
                'ordering': ['codigo'],
            },
        ),
        migrations.AlterModelOptions(
            name='incidencia',
            options={'ordering': ['-urgente', '-creada_en'], 'verbose_name': 'Incidencia'},
        ),
        migrations.AlterModelOptions(
            name='muelle',
            options={'ordering': ['numero'], 'verbose_name': 'Muelle'},
        ),
        migrations.AlterModelOptions(
            name='visit',
            options={'ordering': ['-entrada'], 'verbose_name': 'Visita'},
        ),
        migrations.RemoveField(
            model_name='visit',
            name='agencia',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='agencia_mensajeria',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='bultos_declarados',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='bultos_reales',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='num_pedidos',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='numero_contenedor',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='orden_compra',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='puerto_origen',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='tipo_salida',
        ),
        migrations.AddField(
            model_name='incidencia',
            name='causante',
            field=models.CharField(choices=[('ADMINISTRACION', 'Administración'), ('AGENCIA', 'Agencia transportista'), ('ALMACEN', 'Almacén'), ('CLIENTE', 'Cliente'), ('CHOFER', 'Chofer')], default='AGENCIA', max_length=15),
        ),
        migrations.AddField(
            model_name='incidencia',
            name='concepto_coste',
            field=models.CharField(choices=[('ENVIO', 'Envío'), ('DEVOLUCION', 'Devolución'), ('PARALIZACION', 'Paralización'), ('MANIPULACION', 'Manipulación'), ('SIN_COSTE', 'Sin coste extra')], default='SIN_COSTE', max_length=15),
        ),
        migrations.AddField(
            model_name='visit',
            name='observaciones',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='palets_reales',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='incidencia',
            name='tipo',
            field=models.CharField(choices=[('BOOKING_INCORRECTO', 'Booking incorrecto'), ('DIRECCION_INCORRECTA', 'Dirección incorrecta'), ('ALBARAN_INCORRECTO', 'Albarán incorrecto'), ('DIFERENCIA_PALETS', 'Diferencia de palets'), ('AVERIA', 'Avería del vehículo'), ('PARALIZACIÓN', 'Paralización'), ('ESPERA_EXCESIVA', 'Espera excesiva'), ('OTRO', 'Otro')], max_length=25),
        ),
        migrations.AddField(
            model_name='visit',
            name='chofer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitas', to='accesos.chofer'),
        ),
        migrations.CreateModel(
            name='Expedicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True)),
                ('tipo', models.CharField(choices=[('TRD', 'TRD — Gran cuenta nacional'), ('BLK', 'BLK — Distribuidores / Bulk'), ('BDP', 'BDP — Paquetería pequeña'), ('EXW', 'EXW — Exportación internacional'), ('ENT', 'ENT — Entrada / Recepción')], max_length=5)),
                ('fecha_cita', models.DateField(blank=True, null=True)),
                ('hora_cita', models.TimeField(blank=True, null=True)),
                ('cliente_nombre', models.CharField(blank=True, max_length=200)),
                ('destino', models.CharField(blank=True, max_length=200)),
                ('agencia_nombre', models.CharField(blank=True, max_length=100)),
                ('palets_previstos', models.PositiveIntegerField(blank=True, null=True)),
                ('sga', models.CharField(blank=True, max_length=100, verbose_name='Nº pedido SGA')),
                ('albaran', models.CharField(blank=True, max_length=100)),
                ('observaciones', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('GESTIONADO', 'Gestionado'), ('LANZADO', 'Lanzado'), ('PREPARADO', 'Preparado — listo para cargar'), ('MUELLE', 'En muelle'), ('ENVIADA', 'Enviada'), ('ANULADA', 'Anulada')], default='PENDIENTE', max_length=12)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('agencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expediciones', to='accesos.agencia')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expediciones', to='accesos.cliente')),
                ('muelle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expediciones', to='accesos.muelle')),
                ('hub_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expediciones', to='accesos.hub')),
            ],
            options={
                'verbose_name': 'Expedición',
                'verbose_name_plural': 'Expediciones',
                'ordering': ['fecha_cita', 'hora_cita'],
            },
        ),
        migrations.AddField(
            model_name='visit',
            name='expedicion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitas', to='accesos.expedicion'),
        ),
    ]
