# Generated by Django 6.0.3 on 2026-06-12 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accesos', '0003_agencia_chofer_cliente_hub_alter_incidencia_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecepcionASN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_contenedor', models.CharField(blank=True, max_length=30)),
                ('bill_of_lading', models.CharField(blank=True, max_length=50, verbose_name='Bill of Lading')),
                ('orden_compra', models.CharField(blank=True, max_length=100, verbose_name='Orden de compra')),
                ('proveedor', models.CharField(blank=True, max_length=200)),
                ('puerto_origen', models.CharField(choices=[('VALENCIA', 'Valencia'), ('BARCELONA', 'Barcelona'), ('BILBAO', 'Bilbao'), ('ALGECIRAS', 'Algeciras'), ('VIGO', 'Vigo'), ('OTROS', 'Otros')], default='VALENCIA', max_length=15)),
                ('fecha_llegada_prev', models.DateField(blank=True, null=True, verbose_name='Llegada prevista')),
                ('bultos_declarados', models.PositiveIntegerField(blank=True, null=True)),
                ('bultos_recibidos', models.PositiveIntegerField(blank=True, null=True)),
                ('peso_declarado_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de llegada'), ('EN_PROCESO', 'En proceso de descarga'), ('COMPLETADA', 'Recepción completada'), ('INCIDENCIA', 'Con incidencia')], default='PENDIENTE', max_length=12)),
                ('observaciones', models.TextField(blank=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('cerrada_en', models.DateTimeField(blank=True, null=True)),
                ('expedicion', models.OneToOneField(limit_choices_to={'tipo': 'ENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='asn', to='accesos.expedicion')),
                ('hub_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recepciones', to='accesos.hub')),
            ],
            options={
                'verbose_name': 'Recepción ASN',
                'verbose_name_plural': 'Recepciones ASN',
                'ordering': ['-creada_en'],
            },
        ),
        migrations.CreateModel(
            name='LineaASN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia', models.CharField(max_length=50, verbose_name='Referencia')),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('unidades_declaradas', models.PositiveIntegerField()),
                ('unidades_recibidas', models.PositiveIntegerField(blank=True, null=True)),
                ('lote', models.CharField(blank=True, max_length=50)),
                ('diferencia_ok', models.BooleanField(default=True)),
                ('observaciones', models.CharField(blank=True, max_length=200)),
                ('recepcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='accesos.recepcionasn')),
            ],
            options={
                'verbose_name': 'Línea ASN',
                'verbose_name_plural': 'Líneas ASN',
                'ordering': ['referencia'],
            },
        ),
    ]
